---
title: "PTOS Data Prep"
author: "Matt Carlson"
date: "5/11/2020"
---

```{r, setup}

# devtools::install_github("markfairbanks/tidytable")
# devtools::install_github("ultramattyice/traumaR")
# devtools::install_github("r-lib/vctrs", INSTALL_opts = "--no-multiarch")

pacman::p_load( traumaR,
                tidytable,
                tidymodels,
                ggplot2, 
                ggthemes,
                rlang,
                forcats,
                tictoc, 
                gt, 
                vip, 
                yardstick)

options(scipen=999)  #remove scientific notation
knitr::opts_chunk$set(warning = FALSE, 
                      echo = FALSE)

```

## Load Multiple Data Sources
```{r load_data}

tic()

# raw_data <- fread("~/Data/PTOS_Data.csv", na.strings = c("<unk>", "", "<n/a>")) %>%
#   as.data.table() #%>%   clean_names()

raw_data <- fread("E:/Northwestern/12 - Capstone/PTOS_Data.csv", na.strings = c("<unk>", "", "<n/a>")) %>%
  as.data.table() #%>%   clean_names()

traumaR::run_full_show(raw_data)


toc()

tidytable::inv_gc()

#AWS - 230.08 sec elapsed
#PC  - 380.86 sec elapsed


##################################
# Save files into RData Frames
##################################

dfs<- list("patient_df", "patient_periods",  "ptos_df",  "trans_flat_df" , "trans_full_df")
file_path <- 'E:/Northwestern/12 - Capstone/PTOS_Data/'

for(d in dfs) {
    save(list=d, file=paste0(file_path,d, ".RData"))
}

##################################
# Load all processed RData Frames
##################################

for(d in dfs) {
    load(file = paste0(file_path,d, ".RData"))
}



```



```{r}

patient_df_test <- patient_df %>% 
  mutate.(injury_desc_lvl_0 = case.(injury_desc == 'Motor Vehicle Traffic Accidents', injury_desc, 
                                    injury_desc == 'Accidental Falls', injury_desc, 
                                    injury_desc == 'Other Accidents', injury_desc, 
                                    injury_desc == 'Homicide and Injury Purposely Inflicted By Other Persons', injury_desc, 
                                    injury_desc == 'Motor Vehicle Nontraffic Accidents', injury_desc, 
                                    default = 'Other Injuries'   ))


mvta_lvl_1 <- function(.col){
    .col <- case.(stringr::str_detect(.col, "Driver of MV") == TRUE, 'Driver',
                  stringr::str_detect(.col, "Motorcyclist") == TRUE, 'Motorcyclist',
                  stringr::str_detect(.col, "Pedestrian") == TRUE, 'Pedestrian',
                  stringr::str_detect(.col, "Passenger") == TRUE, 'Passenger',
                  default = 'Other')
    return(.col)
}

mvta_lvl_2 <- function(.col){
  .col <- case.(stringr::str_detect(.col, "Loss Control") == TRUE, 'Loss Control-No Collision', 
                stringr::str_detect(.col, "Highway Collision ") == TRUE, 'Highway Collision ',
                stringr::str_detect(.col, "Collision w/ MV") == TRUE, 'Collision w/ MV',
                stringr::str_detect(.col, "Collision w/ Pedestrian") == TRUE, 'Collision w/ Pedestrian',
                default = 'Other')
  return(.col)
}

otheracc_lvl_2<- function(.col){
    .col <- case.(stringr::str_detect(.col, "Overexertion from sudden strenuous movement") == TRUE, 'Overexertion',
                  stringr::str_detect(.col, "Cutting Object Accident") == TRUE, 'Cutting Object',
                  stringr::str_detect(.col, "Machinery Accident") == TRUE, 'Machinery',
                  stringr::str_detect(.col, "Struck") == TRUE, 'Struck Against',
                  stringr::str_detect(.col, "Firearm") == TRUE, 'Firearm',
                  stringr::str_detect(.col, "Between Objects") == TRUE, 'Caught Between Objects',
                  default = 'Other')
    return(.col)
}


## Accidential Falls


accfall_lvl_2 <- function(.col){
    .col <- case.(stringr::str_detect(.col, "Sports") == TRUE, 'Sports',
                  stringr::str_detect(.col, "Stairs") == TRUE, 'Stairs or Steps',
                  stringr::str_detect(.col, "Pedestrian") == TRUE, 'Pedestrian',
                  stringr::str_detect(.col, "Passenger") == TRUE, 'Passenger',
                  default = 'Other')
    return(.col)
}

accfall_lvl_1 <- function(.data, .var){
  
  .var <- rlang::enquo(.var)

  .data %>%
    separate(., !!.var, c('top_level', 'location'), sep = ' - ') 
  # %>%
  #   case.(stringr::str_detect(top_level, c("Oth Multi-level Fall",
  #                                     'Fall From or Out of Building/Other Structure',
  #                                     'Ladders',
  #                                     'Fall On or From Stairs/Steps')) == TRUE, 'Multi-Level Fall',
  #         stringr::str_detect(top_level, c("Fall From Collision/Push/Shoving","Stairs")) == TRUE, 'Fall From Collision/Push/Shoving',
  #         stringr::str_detect(top_level, "Same Level") == TRUE, 'Same Level Fall',
  #         default = 'Other')

}


split_test <- function(.data, .var) {
  .var <- rlang::enquo(.var)
  
  .data %>% 
    separate.(., !!.var, sep = "-", into = c("col1", "col2")) %>% 
    eval_tidy()
  
}



patient_df_test %>%
  filter.(injury_desc == 'Accidental Falls') %>%
  # filter.(injury_desc == 'Other Accidents') %>%
  # filter.(fltr_fasciotomy == T) %>%
  filter.(peds_adult_flag == 'Peds') %>%
  select.(cause_of_injury_e_code) %>% 
  split_test(., cause_of_injury_e_code)

  # select.(cause_of_injury_e_code, peds_adult_flag, fall_height, fltr_fasciotomy, injury_desc) %>% 
  # filter.(injury_desc %in%  c('Motor Vehicle Traffic Accidents', 'Accidental Falls')) %>%  

  # filter.(fall_height == 'Unknown') %>%
  # separate.(., cause_of_injury_e_code, c('top_level', 'location'), sep = ' - ') 
  accfall_lvl_1(., cause_of_injury_e_code)
  mutate.(func_desc_1 = accfall_lvl_1( cause_of_injury_e_code),
          # func_desc_2 = accfall_lvl_2(cause_of_injury_e_code),
          ) %>% 
  # separate.(cause_of_injury_e_code, c('top_level', 'location'), sep = ' - ') %>% 
  count(  func_desc_1, fltr_fasciotomy,  top_level, location) %>%
  select( func_desc_1, everything.()) %>% 
  pivot_wider.(names_from = fltr_fasciotomy, values_from = n) %>% 
  arrange(top_level) #-`TRUE`)

```



# Forearm Surgeries that results in Fasciotomy

```{r fasciotomy_results}

patient_df %>% 
  select.(forearm_fx_desc, fasciotomy_desc) %>% 
  filter.(!is.na(forearm_fx_desc)) %>% 
  mutate.(fasciotomy = ifelse.(is.na(fasciotomy_desc), 'no_fasc', 'yes_fasc')) %>% 
  summarize.(total = n.(), by = c(forearm_fx_desc, fasciotomy)) %>%
  arrange.(-total) %>% 
  pivot_wider.(names_from = fasciotomy, values_from = total) %>% 
  mutate.(total_no = no_fasc/sum(no_fasc, na.rm = TRUE), 
          total_yes = yes_fasc/sum(yes_fasc, na.rm = TRUE)) %>% 
  arrange.(-total_yes, forearm_fx_desc, ) %>% 
  select.(forearm_fx_desc, yes_fasc, total_yes, no_fasc, total_no) %>% 
  gt(
    rowname_col = 'forearm_fx_desc'
    ) %>% 
  tab_header(
    title = md("Forearm Procedures which have Fasciotomy"),
    subtitle = md("PTOS Data")
  ) %>% 
  tab_spanner(
    label = "Fasciotomy", 
    columns = vars(yes_fasc, total_yes)
  ) %>% 
  tab_spanner(
    label = "No Fasciotomy", 
    columns = vars(no_fasc, total_no)
  ) %>% 
  cols_label(yes_fasc = "#", 
             total_yes = "% of Total", 
             no_fasc = "#", 
             total_no = "% of Total") %>%
  fmt_percent(vars(total_yes, total_no), decimals = 1) %>% 
  fmt_number(vars(yes_fasc, no_fasc), decimals = 0) %>% 
  summary_rows(columns = vars( total_yes, total_no),
               fns = list(Total = ~sum(.)),
               formatter = fmt_percent,
               decimals = 1) %>%
  summary_rows(columns = vars(yes_fasc,  no_fasc),
               fns = list(Total = ~sum(.)),
               formatter = fmt_number,
               decimals = 0)
  
  
```

## Procedure Results by Forearm Surgeries

```{r proc}

fx_list <- patient_periods %>% 
  filter.(fltr_procedure == T, 
          fltr_fasciotomy == T) %>% 
  select.(id, fltr_fasciotomy, peds_adult_flag, fltr_procedure, sex, race, age_in_yrs, injury_desc) %>% 
  distinct.()

fx_proc <- trans_full_df %>% 
  mutate.(data_source = as_factor(data_source), 
          data_source = fct_relevel(data_source, c('arrival/discharge', 'diagnosis', 'procedure', 'complications' ))) %>% 
  inner_join.(fx_list, by = 'id')

data_quality_check <- data.table(procedures = fx_proc %>%  distinct.(id) %>% summarize.(cnt = n.()), 
                      patients = fx_list %>% summarize.(cnt = n.())) %>% 
  mutate.(diff = patients.cnt - procedures.cnt)

data_quality_check

tidytable::inv_gc()

fx_proc <- fx_proc %>% 
  arrange.(id, date, data_source, time ) %>% 
  filter.(data_source %notin% c('transport', 'arrival/discharge'))  %>% 
  mutate.(index = seq_len(.N), by = id ) %>% 
  select.(index, id, everything.()) 


fx_proc %>% 
  select.(id, peds_adult_flag) %>% 
  distinct.() %>% 
  count(peds_adult_flag) %>% 
  mutate(props = n/sum(n))


```


```{r}

library(leaps)


model_df <- fx_proc %>% 
  mutate.(fltr_fasciotomy = as_factor(fltr_fasciotomy)) %>%
  select.(-date, -time, -index, -code_desc, -code_cd, -id, -data_source, -chapter_desc, -fltr_procedure) %>% 
  as_tibble() %>% 
  na.omit() %>% 
  head(2000)


reg_1 <- regsubsets(fltr_fasciotomy ~ subchapter_desc * race * injury_desc,
  data = model_df, nvmax = 4, really.big=T, method = "backward")

summary(reg_1)


```



## Woe Binning
```{r}


library(woeBinning)




df <- fx_proc %>% 
  drop_na.() %>% 
  select(fltr_fasciotomy, subchapter_desc, chapter_desc, injury_desc, code_desc, sex) %>% 
  mutate(subchapter_desc = as.factor(subchapter_desc), 
         injury_desc = as.factor(injury_desc)) %>% 
  group_by(fltr_fasciotomy, subchapter_desc, chapter_desc, injury_desc, code_desc, sex) %>% 
  summarise(cnt = n())

select_cols <- df %>% 
  count(chapter_desc, subchapter_desc) %>% 
  mutate(props = n/sum(n)) %>% arrange(props) %>%  
  filter(n >1) %>% 
  pull(chapter_desc)

df <- df %>% filter(chapter_desc %in% select_cols)


df %>% 
  count(chapter_desc) %>% 
  mutate(props = n/sum(n)) %>% arrange(props)


binning <- woe.tree.binning(df, 
                 target.var = 'fltr_fasciotomy', 
                 pred.var = c( 'injury_desc', 'chapter_desc'),  
                 event.class='FALSE')


df %>% 
  count(chapter_desc) %>% 
  mutate(props = n/sum(n))


woe.binning.plot(binning)
tabulate.binning <- woe.binning.table(binning)
tabulate.binning


df_woe <- woe.binning.deploy(df, 
                             binning, 
                             add.woe.or.dum.var = 'woe')

df_woe %>% 
  count(subchapter_desc.binned, injury_desc.binned, fltr_fasciotomy) %>% 
  mutate(props = n/sum(n)) %>% 
  gt(rowname_col = 'subchapter_desc.binned', 
      groupname_col = 'injury_desc.binned' )


df_woe %>% 
  count(fltr_fasciotomy) %>% 
  mutate(props = n/sum(n))

```

## Using TidyModel FrameWork from Max Kuhn
* Need to bin the procedures together
* Need to bin the injuries together

```{r tidymodel_wf}

model_df <- fx_proc %>% 
  mutate.(fltr_fasciotomy = as_factor(fltr_fasciotomy),
          # date = lubridate::mdy(date), 
          # dow = as_factor(lubridate::wday(date, label = TRUE))
          ) %>%
  select.(-date, -time, -index, -code_desc, -code_cd, -id, -data_source, -chapter_desc, -fltr_procedure) %>% 
  as_tibble() %>% 
  na.omit() %>% 
  head(2000)


set.seed(123)
train_test_split <- rsample::initial_split(data = model_df, 
                                           strata = injury_desc)

train_df <- train_test_split %>% training() 
test_df  <- train_test_split %>% testing()

train_df %>% 
  count(loc_desc) %>% 
  mutate(props = n/sum(n))

test_df %>% 
  count(fltr_fasciotomy) %>% 
  mutate(props = n/sum(n))


set.seed(234)
val_set <- validation_split(train_df, 
                            strata = injury_desc,
                            prop = 0.80)
val_set

cores <- parallel::detectCores()-1

rf_mod <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_engine("ranger", num.threads = cores) %>% 
  set_mode("classification")

rf_recipe <- 
  recipe(fltr_fasciotomy ~ ., data = train_df) %>%
  # check_missing(subchapter_desc, injury_desc ) %>% 
  # update_role(chapter_desc, fltr_procedure, new_role = 'ID' ) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_naomit(all_predictors()) %>% 
  step_novel(all_nominal()) %>% 
  step_modeimpute(all_nominal())

rf_workflow <- 
  workflow() %>% 
  add_model(rf_mod) %>% 
  add_recipe(rf_recipe)


rf_mod %>%    
  parameters()

set.seed(345)
rf_res <- 
  rf_workflow %>% 
  tune_grid(val_set,
            grid = 10,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

rf_res %>% 
  show_best(metric = "roc_auc")

# autoplot(rf_res)


rf_best <- 
  rf_res %>% 
  select_best(metric = "roc_auc")

rf_auc <- 
  rf_res %>% 
  collect_predictions(parameters = rf_best) %>% 
  roc_curve(fltr_fasciotomy, .pred) %>% 
  mutate(model = "Random Forest")

rf_auc %>% 
# bind_rows(rf_auc, lr_auc) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, col = model)) + 
  geom_path(lwd = 1.5, alpha = 0.8) +
  geom_abline(lty = 3) + 
  coord_equal() + 
  scale_color_viridis_d(option = "plasma", end = .6)

```




